#!/bin/sh

XRESOURCES="/home/adrian/.xresources"

if [ -f "$XRESOURCES" ]; then
	xrdb "$XRESOURCES"
fi

xmodmap /home/adrian/.config/kb/neo.xmodmap

sxhkd -c /home/adrian/.sxhkdrc &

~/.fehbg &

exec sh -c 'while :; do sleep 10; done'
