#!/bin/sh

#maybe try out backgrounds by xsetroot

xsetroot -cursor_name left_ptr

setxkbmap lv
xmodmap $HOME/.xmodmap
xset -r 51

bgs -R -C '#fefefe' '/usr/local/img/reward.png'
xflux -l 48.1 -g 11.6
slstatus &
batwatch &

exec dwm
