#!/bin/sh

XRESOURCES="/home/adrian/.xresources"

if [ -f "$XRESOURCES" ]; then
	xrdb "$XRESOURCES"
fi

xsetroot -name geb
xsetroot -cursor_name left_ptr

xmodmap /home/adrian/.config/kb/neo.xmodmap

barinfo | lemonbar -g $(echo $(wattr w $(lsw -r)) '-2*' "$BW" '-10' | bc)"x16+5+5" -B '#ffffff' -F '#000000' &
feh --no-fehbg --image-bg black --bg-fill '/usr/share/wall/bomb.jpg'
sxhkd -c /home/adrian/.sxhkdrc &
wew | yawee.sh &

#ignore all bars
barign &

#set up the papparazi
pprz &

exec sh -c 'while :; do sleep 10; done'
